# Generated by Django 4.2.5 on 2023-11-01 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre1', models.CharField(choices=[('ROCK', 'Rock'), ('POP', 'Pop'), ('ELECTRONICA', 'Electronica'), ('HIPHOP', 'Hip Hop'), ('REGGAE', 'Reggae'), ('REGGAETON', 'Reggaeton'), ('CUMBIA', 'Cumbia'), ('SALSA', 'Salsa'), ('TANGO', 'Tango'), ('FOLKLORE', 'Folklore'), ('JAZZ', 'Jazz'), ('BLUES', 'Blues'), ('OTRO', 'Otro')], max_length=50)),
                ('genre2', models.CharField(choices=[('ROCK', 'Rock'), ('POP', 'Pop'), ('ELECTRONICA', 'Electronica'), ('HIPHOP', 'Hip Hop'), ('REGGAE', 'Reggae'), ('REGGAETON', 'Reggaeton'), ('CUMBIA', 'Cumbia'), ('SALSA', 'Salsa'), ('TANGO', 'Tango'), ('FOLKLORE', 'Folklore'), ('JAZZ', 'Jazz'), ('BLUES', 'Blues'), ('OTRO', 'Otro')], max_length=50)),
                ('genre3', models.CharField(choices=[('ROCK', 'Rock'), ('POP', 'Pop'), ('ELECTRONICA', 'Electronica'), ('HIPHOP', 'Hip Hop'), ('REGGAE', 'Reggae'), ('REGGAETON', 'Reggaeton'), ('CUMBIA', 'Cumbia'), ('SALSA', 'Salsa'), ('TANGO', 'Tango'), ('FOLKLORE', 'Folklore'), ('JAZZ', 'Jazz'), ('BLUES', 'Blues'), ('OTRO', 'Otro')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
