# Generated by Django 4.2.5 on 2023-11-01 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_userpreferences_genre1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='genre1',
            field=models.CharField(blank=True, choices=[('ROCK', 'Rock'), ('POP', 'Pop'), ('ELECTRO', 'Electro'), ('HIPHOP', 'Hip Hop'), ('REGGAE', 'Reggae'), ('REGGAETON', 'Reggaeton'), ('CUMBIA', 'Cumbia'), ('SALSA', 'Salsa'), ('TANGO', 'Tango'), ('FOLKLORE', 'Folklore'), ('JAZZ', 'Jazz'), ('BLUES', 'Blues'), ('OTRO', 'Otro')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='genre2',
            field=models.CharField(blank=True, choices=[('ROCK', 'Rock'), ('POP', 'Pop'), ('ELECTRO', 'Electro'), ('HIPHOP', 'Hip Hop'), ('REGGAE', 'Reggae'), ('REGGAETON', 'Reggaeton'), ('CUMBIA', 'Cumbia'), ('SALSA', 'Salsa'), ('TANGO', 'Tango'), ('FOLKLORE', 'Folklore'), ('JAZZ', 'Jazz'), ('BLUES', 'Blues'), ('OTRO', 'Otro')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='genre3',
            field=models.CharField(blank=True, choices=[('ROCK', 'Rock'), ('POP', 'Pop'), ('ELECTRO', 'Electro'), ('HIPHOP', 'Hip Hop'), ('REGGAE', 'Reggae'), ('REGGAETON', 'Reggaeton'), ('CUMBIA', 'Cumbia'), ('SALSA', 'Salsa'), ('TANGO', 'Tango'), ('FOLKLORE', 'Folklore'), ('JAZZ', 'Jazz'), ('BLUES', 'Blues'), ('OTRO', 'Otro')], max_length=50, null=True),
        ),
    ]
