# Generated by Django 4.2.5 on 2023-10-19 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicloversuser',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
