# Generated by Django 4.2.5 on 2023-10-19 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('logo', models.ImageField(upload_to='business-logos/')),
                ('banner', models.ImageField(upload_to='business-banners/')),
                ('address', models.CharField(blank=True, max_length=100)),
                ('neighbourhood', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250)),
                ('rating', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BusinessPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='business-images/')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('banner', models.ImageField(blank=True, upload_to='events-banners/')),
                ('address', models.CharField(blank=True, max_length=100)),
                ('neighbourhood', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('datetime', models.DateTimeField()),
                ('artist', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('ROCK', 'Rock'), ('POP', 'Pop'), ('ELECTRONICA', 'Electronica'), ('HIPHOP', 'Hip Hop'), ('REGGAE', 'Reggae'), ('REGGAETON', 'Reggaeton'), ('CUMBIA', 'Cumbia'), ('SALSA', 'Salsa'), ('TANGO', 'Tango'), ('FOLKLORE', 'Folklore'), ('JAZZ', 'Jazz'), ('BLUES', 'Blues'), ('OTRO', 'Otro')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EventPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='events-images/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250)),
                ('rating', models.PositiveSmallIntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.event')),
            ],
        ),
    ]
