# Generated by Django 4.2.5 on 2023-10-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='logo',
            field=models.ImageField(upload_to='business-logos/'),
        ),
    ]
