# Generated by Django 4.2.5 on 2023-10-14 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_alter_business_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessphoto',
            name='photo',
            field=models.ImageField(upload_to='business-images/'),
        ),
        migrations.AlterField(
            model_name='eventphoto',
            name='photo',
            field=models.ImageField(upload_to='business-logos/'),
        ),
    ]
