# Generated by Django 4.2.5 on 2023-11-01 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='genre',
            field=models.CharField(choices=[('ROCK', 'Rock'), ('POP', 'Pop'), ('ELECTRO', 'Electro'), ('HIPHOP', 'Hip Hop'), ('REGGAE', 'Reggae'), ('REGGAETON', 'Reggaeton'), ('CUMBIA', 'Cumbia'), ('SALSA', 'Salsa'), ('TANGO', 'Tango'), ('FOLKLORE', 'Folklore'), ('JAZZ', 'Jazz'), ('BLUES', 'Blues'), ('OTRO', 'Otro')], max_length=50),
        ),
    ]
