# Generated by Django 4.2.5 on 2023-11-05 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_alter_event_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2023-10-01'),
            preserve_default=False,
        ),
    ]
