# Generated by Django 4.2.5 on 2023-11-05 22:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_eventcomment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
