# Generated by Django 4.2.5 on 2023-11-08 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_businesscomment_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventcomment',
            name='rating',
        ),
    ]
